
spring:
  datasource:
    url: jdbc:mysql:///my_student
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: stu_service
  registry:
    address: zookeeper://192.168.47.130:2181
  protocol:
    port: 20885
  consumer:
    check: false


server:
  port: 8081

