
spring:
  datasource:
    url: jdbc:mysql:///my_classes
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: class_service
  registry:
    address: zookeeper://192.168.47.130:2181
  protocol:
    port: 20889
server:
  port: 8082
